# This file was generated by GoReleaser. DO NOT EDIT.
class Ttimer < Formula
  desc ""
  homepage "https://github.com/drgrib/ttimer"
  version "1.0.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/drgrib/ttimer/releases/download/v1.0.7/ttimer_1.0.7_darwin_amd64.tar.gz"
    sha256 "59dc6954ac5259f793511e7e203edaf5b72f2e02e2aa41c2150b9ba86e4dd7f7"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/drgrib/ttimer/releases/download/v1.0.7/ttimer_1.0.7_linux_amd64.tar.gz"
      sha256 "9c84d89aaaa6e587c48cffa261351a3239f8bcdd1a9226d62fbc79b778ff2304"
    end
  end

  def install
    bin.install "ttimer"
  end
end
