# This file was generated by GoReleaser. DO NOT EDIT.
class Ttimer < Formula
  desc ""
  homepage "https://github.com/drgrib/ttimer"
  version "1.0.8"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/drgrib/ttimer/releases/download/v1.0.8/ttimer_1.0.8_darwin_amd64.tar.gz"
    sha256 "3b71f0266aff43c3e7befc31e87d581afa62a54f68b7ef86e1cf3fb96366f0e7"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/drgrib/ttimer/releases/download/v1.0.8/ttimer_1.0.8_linux_amd64.tar.gz"
      sha256 "489938bc0cced9ec2c74f1fc2e9fffeda6b61f25ccf5c7f4cd11ba205d5b094b"
    end
  end

  def install
    bin.install "ttimer"
  end
end
